# Generated by Django 5.1.3 on 2024-11-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='generacion',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
